### PR TITLE
add OP-Response-token_type test, see: openid-certification/oidctest#89

### PR DESCRIPTION
**Pull request by zandbelt**

### CODE REVIEW

**Comment by rohe** [comment]
That the Travis build failed is that for you or Filip to fix ?

**Comment by panva** [comment]
Nop. Having a test extra doesnt matter. Not having it does :)

**Comment by zandbelt** [comment]
because *somebody* thought it was better to do so: https://github.com/openid-certification/oidctest/issues/89#issuecomment-389909152

...

**Comment by panva** [comment]
Well. Yeah :( hahaha

**Comment by zandbelt** [comment]
But I'm open to reconsider

**Comment by panva** [comment]
Up to you, really

**Comment by zandbelt** [comment]
On 2nd thought I think I favor your 2nd line of reasoning :-)

It would not make sense for a certification suite to allow non-conformant requests like regular "OP-Response-code" to pass if there's no `token_type` just because it tests for something else. Every response should have it and thus should be checked an no explicit test need to exist. Please ignore this PR and @panva you my revert the commit that added the `token_type` test into the conformance tests.

**Comment by panva** [comment]
For interop, shall we do a warning when expires_in is missing too? Its RECOMMENDED

**Pull request closed without merging**
